# Estadística descriptiva para Iris

## Entendimiento de los datos

In [13]:
# Cargar librerias
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px

import plotly.io as pio
pio.templates.default = "plotly"

In [14]:
# Cargar dataset
df = pd.read_csv("https://raw.githubusercontent.com/jsaraujott/datos/refs/heads/main/iris.csv")
df["type"] = df["type"].astype(str)

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   type          150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.1 KB

In [16]:
df.sample(10)

     sepal_length  sepal_width  petal_length  petal_width type
52            6.9          3.1           4.9          1.5    1
55            5.7          2.8           4.5          1.3    1
80            5.5          2.4           3.8          1.1    1
66            5.6          3.0           4.5          1.5    1
63            6.1          2.9           4.7          1.4    1
29            4.7          3.2           1.6          0.2    0
148           6.2          3.4           5.4          2.3    2
118           7.7          2.6           6.9          2.3    2
69            5.6          2.5           3.9          1.1    1
46            5.1          3.8           1.6          0.2    0

In [17]:
df.describe().round(1)

       sepal_length  sepal_width  petal_length  petal_width
count         150.0        150.0         150.0        150.0
mean            5.8          3.1           3.8          1.2
std             0.8          0.4           1.8          0.8
min             4.3          2.0           1.0          0.1
25%             5.1          2.8           1.6          0.3
50%             5.8          3.0           4.4          1.3
75%             6.4          3.3           5.1          1.8
max             7.9          4.4           6.9          2.5

In [18]:
# Seleccionar 2 variables cualquiera
opciones = list(df.columns)[0:4]
v = (opciones[0],opciones[2])

## Distribuciones de variables

In [19]:
# Visualizar histograma de variable 1
hist_plot01 = px.histogram(
    df, 
    x = v[0], 
    title = f"Distribución {v[0]}", 
    color = "type", 
    marginal = "box", 
    width = 700, 
    height = 400
)
hist_plot01.show()

In [20]:
# Calcular estadisticos de variable 1
prom1 = np.mean(df[v[0]])
med1 = np.median(df[v[0]])
desv1 = np.std(df[v[0]])
print("Media: {:.1f}".format(prom1))
print("Mediana: {:.1f}".format(med1))
print("Desviación: {:.1f}".format(desv1))

Media: 5.8
Mediana: 5.8
Desviación: 0.8

In [21]:
# Visualizar histograma de variable 2
hist_plot02 = px.histogram(
    df, 
    x = v[1], 
    title = f"Distribución {v[1]}", 
    color = "type", 
    marginal = "box", 
    width = 700, 
    height = 400
)
hist_plot02.show()

In [ ]:
# Calcular estadisticos de variable 2
prom2 = np.mean(df[v[1]])
med2 = np.median(df[v[1]])
desv2 = np.std(df[v[1]])
print("Media: {:.1f}".format(prom2))
print("Mediana: {:.1f}".format(med2))
print("Desviación: {:.1f}".format(desv2))

Media: 3.8
Mediana: 4.3
Desviación: 1.8

## Relación de variables

In [23]:
# Visualizar dispersion entre variables
disp_plot = px.scatter(
    df, 
    x = v[0], 
    y = v[1], 
    color = "type", 
    title = f"Dispersión {v[1]} vs. {v[0]}", 
    width = 700, 
    height = 400
)
disp_plot.show()

In [24]:
# Calcular correlacion entre variables
correl = np.corrcoef(df[v[0]],df[v[1]])
print("Correlación de Pearson: {:.1%}".format(correl[0,1]))

Correlación de Pearson: 87.2%